#pragma config(Sensor, in1,    potentiometer,  sensorPotentiometer)
#pragma config(Motor,  port2,           leftWheel,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           rightWheel,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           carrier,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           armLeft,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           armRight,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           claw,          tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

//************************
//       VARIABLES
//************************
int leftMotorSpeed = 0;
int rightMotorSpeed = 0;


//*************************
//         METHODS
//*************************

//***** AUTONOMOUS *****

/***** MOVEMENT *****/

//move the robot forward or backward
//wheelPower is how fast the robot goes, values -127 to 127 are acceptable
	//if wheelPower is positive, robot goes forwards
	//if wheelPower is negative, robot goes backwards
//curve is how much the robot should turn tbd how the robot will use that value to turn though...
void moveWheels(int wheelPower)
{
	leftMotorSpeed = wheelPower;
	rightMotorSpeed = -wheelPower-1;
	motor[leftFrontMotor] = leftMotorSpeed;
	motor[leftBackMotor] = leftMotorSpeed;
	motor[rightFrontMotor] = rightMotorSpeed;
	motor[rightBackMotor] = rightMotorSpeed;
}

//turn in place
//power is what direction and how fast to turn, values -127 to 127 are acceptable
	//if power is a positive integer it goes clockwise
	//if power is a negative integer it goes counterclockwise
void turn(int power)
{
	motor[leftFrontMotor] = -power;
	motor[leftBackMotor] = -power;
	motor[rightFrontMotor] = -power;
	motor[rightBackMotor] = -power;
}

//stops wheel motors so robot stops moving
void stopWheels(){
	motor[leftFrontMotor] = 0;
	motor[leftBackMotor] = 0;
	motor[rightFrontMotor] = 0;
	motor[rightBackMotor] = 0;
}

//***** CLAW *****

//opens the claw that will pick up the cones we will place on the mobile goal
//since it is the same claw as last year, for convenience I will use the same code once I get the chance
void openClaw()
{
	motor[claw] = 35;
	sleep(1100);
	motor[claw] = 0;
}

//closes the claw that will pick up the cones we will place on the mobile goal
//since it is the same claw as last year, for convenience I will use the same code once I get the chance
void closeClaw(int power)
{
	motor[claw] = -power;
	sleep(700);
	motor[claw] = 0;
}

//***** ARM *****

/*

*/
int armPower = 30;
int horizontal = 120;
int gravConst = 40;
int bottom = 750;
void moveArm(int speed) {
  int gravity = gravConst-abs(horizontal-SensorValue[pot])*gravConst/600;

  motor[armLeft] = -(speed+gravity);
  motor[armRight] = speed+gravity;
}

//lifts up a yellow cone in its claw and holds it mid air
void liftCone()
{
	motor[claw] = -45;
	sleep(750);
	motor[claw] = -20;
	motor[armLeft] = -110;
	motor[armRight] = 110;
	//wait 1 second
	sleep(1000);
	//stop motors
	motor[armLeft] = -30;
	motor[armRight] = 30;
}

//places the cone the robot is holding midair on the mobile goal in front of it
void coneOnMobileGoal()
{
	//move arm motors until cone on goal
	motor[armLeft] = -10;
	motor[armRight] = 10;
	sleep(2500);	//wait .25 seconds
	motor[armLeft] = -30;
	motor[armRight] = 30;
	//let go of cone
	openClaw();
}

void auto2()
{
	closeClaw(35);
	liftCone();
	moveWheels(50);
	sleep(3500);
	stopWheels();
	coneOnMobileGoal();
	moveWheels(50);
	sleep(1750);
	stopWheels();
}

//what to do during autonomous period
void auto()
{
		//go straight until you reach white line
		moveWheels(50);
		sleep(2800);
		stopWheels();
	  //turn 20 degrees? right
		turn(30);
		sleep(500);
		stopWheels();
		closeClaw(35);
		moveWheels(-30);
		sleep(200);
		stopWheels();
		//open claw
		openClaw();
		moveWheels(30);
		sleep(800);
		stopWheels();
		//pick up cone
		liftCone();
		//turn back 20 degrees left (or however much you turned before)
		turn(-40);
		sleep(500);
		stopWheels();
		moveWheels(20);
		sleep(200);
		stopWheels();
		//place cone on mobile goal
		coneOnMobileGoal();
		//maybe ready robot for driver phase
}

//***** DRIVING *****

int modify(int input) {
	//return pow(input,3)/16384;
  return (input+(pow(input,5)/8192-pow(input,3))/8192)/3;
}

//move the wheels depending on the values sent from the right and left joysticks
//tank controls used
	//left joystick moves left wheel
	//right joystick moves right wheel
	//joystick up moves wheel forward
	//joystick down moves that wheel backward
	//move robot straight forward = left and right forward
	//move robot straight backward = left and right backward
	//pivot robot left = left backward, right forward
	//pivot robot right = left forward, right backward
	//car turn left = left not moved, right forward
	//car turn right = left forward, right not moved
	//left curve = left and right forward, but right is more forward than the other
	//right curve = left and right forward, but left is more forward than the other
void moveWheels(){
	//original speed constants were .5, kept the same at request from testing
	motor[leftWheel] = modify(vexRT[Ch3]);
	motor[rightWheel] = -modify(vexRT[Ch2]);
}

//opens or closes claw
	//if 6U is pressed, it opens
	//if 6D is pressed, it closes
void updateClaw()
{
    if(vexRT[Btn6U] == 1) // If upper Z button down
        motor[claw] = 25;
    else if(vexRT[Btn6D] == 1) // If lower Z button down
        motor[claw] = -25;
    else
    	motor[claw] = 0;
}

//raises, lowers, or stops moving the arm depending if button 5U, 5D, or neither are pressed
	//5U raises arm
	//5D lowers arm
void updateArm()
{
	int power = 0;

	if(vexRT[Btn5D] == 1) //if left lower Z button is pressed
	{
		power += 1;
		motor[armLeft] = -7-power;
		motor[armRight] = 6+power;
	}
	else if((SensorValue[potentiometer] <= 0)||((vexRT[Btn5U] == 0) && (vexRT[Btn5D] == 0)))
	{
		motor[armLeft] = -30;
		motor[armRight] = 30;
	}
  else if(vexRT[Btn5U] == 1) //if left upper Z button is pressed
	{
		power += 60;
		motor[armLeft] = -50-power;
		motor[armRight] = 50+power;
	}

}


//method to raise arm but can't do anything else until it stops moving
//supposed to be used with if(vexRT[Btn5U] == 1)
//just here in case updateArm doesn't work out
//void raiseArm(){
//	motor[armLeft] = 50;
//	motor[armRight] = -50;
//	waitUntil(vexRT[Btn5U] == 0);
//	motor[armLeft] = 0;
//	motor[armRight] = 0;
//}

//method to lower arm but can't do anything else until it stops moving
//supposed to be used with if(vexRT[Btn5D] == 1)
//just here in case updateArm doesn't work out
//void lowerArm(){
//	motor[armLeft] = -50;
//	motor[armRight] = 50;
//	waitUntil(vexRT[Btn5D] == 0);
//	motor[armLeft] = 0;
//	motor[armRight] = 0;
//}

//lifts the mobile goal, needs to be heavily tested
void raiseCarrier()
{
	//move carrier motors at speed so it should difinitely be able to lift the mobile goal
	motor[carrier] = 100;
	//wait 1 second, needs to be tested and probably changed but this is the test value
	sleep(1000);
	//stop carrier motors
	motor[carrier] = 0;
}

//lowers the mobile goal, needs to be heavily tested
void lowerCarrier()
{
	//move carrier motors at the same descending speed the arm has, 6
	motor[carrier] = -50;
	//wait 1 second, needs to be tested and probably changed but this is the test value
	sleep(1000);
	//stop carrier motors
	motor[carrier] = 0;
}

//raises or lowers the mobile goal carrier depending if button 8D, 8R, or neither are pressed
	//8D lifts mobile goal
	//8R lowers mobile goal
void updateMobileGoal()
{
	if(vexRT[Btn8D] == 1)
		raiseCarrier();
	else if(vexRT[Btn8R] == 1)
		lowerCarrier();
}


//claw - 6U opens
// 6D close
//arm - 5U raises up
// 5D lowers
//mobile goal
//8D raises
//8R lowers
//left and right joysticks controls wheels with tank controls

//make sure main() is the last "task", weird C mechanic
task main()
{
	//apparently does not compile, but book says "this command should be the first thing in your "task main()" so idk
	//will not set up any motors and sensors, you must manually set the motos and sensors in the 'Motors and Sensors Setup' menu
	//robotType();

	//only two motors will be used for the base so we can use the rest to lift the cones and mobile goal

	while(true){
		moveWheels();
		updateClaw();
		updateArm();
		updateMobileGoal();
	}
}


//*************************
//          TASKS
//*************************

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
  auto2();
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
  // User control code here, inside the loop
	//waitUntil(vexRT[Btn8R] == 1)
	//auto();

  while (true)
  {
    moveWheels();
		updateClaw();
		updateArm();
  }
}
