#pragma config(Sensor, in1,             armPot,          sensorPotentiometer)
#pragma config(Motor,  port2,           leftFrontWheel,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           rightFrontWheel, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           leftBackWheel,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           rightBackWheel,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           armLeft,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           armRight,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           claw,            tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//declare variables below
int clawPower = 35;
int armPower = 50;
int gravConstant = 20;

void moveWheels(int left, int right)
{
	motor[leftFrontWheel] = .5*left;
  motor[leftBackWheel] = .5*left;
  motor[rightFrontWheel] = .5*-right;
  motor[rightBackWheel] = .5*-right;
}

void moveClaw(bool open, bool close)
{
    if(open) // If upper Z button down
        motor[claw] = clawPower;
    else if(close) // If lower Z button down
        motor[claw] = -clawPower;
    else
    	motor[claw] = 0;
}

/*
armAngle 2048 -> 0
4096 -> gravConstant
0 -> -gravConstant
*/
void moveArm(int armAngle, bool lift, bool lower){

	int gravity = gravConstant * (armAngle - 2048)/2048;

	if(lift) //if left upper Z button is pressed
	{
		motor[armLeft] = -armPower - gravity;
		motor[armRight] = armPower + gravity;
	}
	else if(lower) //if left lower Z button is pressed
	{
		motor[armLeft] = armPower - gravity;
		motor[armRight] = -armPower + gravity;
	}
	else
	{
		motor[armLeft] = -gravity;
		motor[armRight] = gravity;
	}
}

//claw - 6U opens
// 6D close
//arm - 5U raises up
// 5D lowers
//mobile goal
//8D raises
//8R lowers
//left joystick controls wheels

//make sure main() is the last "task", weird C mechanic
task main()
{
	//apparently does not compile, but book says "this command should be the first thing in your "task main()" so idk
	//will not set up any motors and sensors, you must manually set the motos and sensors in the 'Motors and Sensors Setup' menu
	//robotType();
	//only two motors will be used for the base so we can use the rest to lift the cones and mobile goal

	while(true){
		moveWheels(vexRT[Ch3], vexRT[Ch2]);
		moveArm(SensorValue[in1], vexRT[Btn5U] == 1, vexRT[Btn5D] == 1);
		moveClaw(vexRT[Btn6U] == 1, vexRT[Btn6D]);

	}
}
