#pragma config(Sensor, in2,    lineTracker,    sensorLineFollower)
#pragma config(Motor,  port2,           leftFrontMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           rightFrontMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           leftBackMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           rightBackMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           armLeft,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           armRight,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           claw,          tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

//************************
//       VARIABLES
//************************
int leftMotorSpeed = 0;
int rightMotorSpeed = 0;


//*************************
//         METHODS
//*************************

//***** AUTONOMOUS *****

/***** MOVEMENT *****/

//move the robot forward or backward
//wheelPower is how fast the robot goes, values -127 to 127 are acceptable
	//if wheelPower is positive, robot goes forwards
	//if wheelPower is negative, robot goes backwards
//curve is how much the robot should turn tbd how the robot will use that value to turn though...
void moveWheels(int wheelPower)
{
	leftMotorSpeed = wheelPower;
	rightMotorSpeed = -wheelPower;
	motor[leftFrontMotor] = leftMotorSpeed;
	motor[leftBackMotor] = leftMotorSpeed;
	motor[rightFrontMotor] = rightMotorSpeed;
	motor[rightBackMotor] = rightMotorSpeed;
}

//turn in place
//power is what direction and how fast to turn, values -127 to 127 are acceptable
	//if power is a positive integer it goes clockwise
	//if power is a negative integer it goes counterclockwise
void turn(int power)
{
	motor[leftFrontMotor] = -power;
	motor[leftBackMotor] = -power;
	motor[rightFrontMotor] = -power;
	motor[rightBackMotor] = -power;
}

//stops wheel motors so robot stops moving
void stopWheels(){
	motor[leftFrontMotor] = 0;
	motor[leftBackMotor] = 0;
	motor[rightFrontMotor] = 0;
	motor[rightBackMotor] = 0;
}

//***** CLAW *****

//opens the claw that will pick up the cones we will place on the mobile goal
//since it is the same claw as last year, for convenience I will use the same code once I get the chance
void openClaw()
{
	motor[claw] = 35;
	sleep(1100);
	motor[claw] = 0;
}

//closes the claw that will pick up the cones we will place on the mobile goal
//since it is the same claw as last year, for convenience I will use the same code once I get the chance
void closeClaw(int power)
{
	motor[claw] = -power;
	sleep(750);
	motor[claw] = 0;
}

//***** ARM *****

//lifts up a yellow cone in its claw and holds it mid air
void liftCone()
{
	closeClaw(45);
	motor[armLeft] = -110;
	motor[armRight] = 110;
	//wait 1 second
	sleep(1000);
	//stop motors
	motor[armLeft] = -30;
	motor[armRight] = 30;
}

//places the cone the robot is holding midair on the mobile goal in front of it
void coneOnMobileGoal()
{
	//move arm motors until cone on goal
	motor[armLeft] = -80;
	motor[armRight] = 79;
	sleep(400);	//wait .25 seconds
	motor[armLeft] = -30;
	motor[armRight] = 30;
	//let go of cone
	openClaw();
}

//what to do during autonomous period
void auto()
{
		//go straight until you reach white line
		moveWheels(50);
		sleep(3500);
		stopWheels();
		//turn 20 degrees? right
		turn(30);
		sleep(500);
		stopWheels();
		//close claw
		moveWheels(-30);
		sleep(1000);
		stopWheels();
		closeClaw(35);
		//open claw
		openClaw();
		//pick up cone
		liftCone();
		//turn back 20 degrees left (or however much you turned before)
		turn(-30);
		sleep(500);
		stopWheels();
		//move forward until you reach colored square where mobile goal is
		moveWheels(50);
		sleep(500);
		stopWheels();
		//place cone on mobile goal
		coneOnMobileGoal();
		//maybe ready robot for driver phase
}

//***** DRIVING *****

//drives wheels with two joysticks
	//left and right forward = straight forward movement
	//left and right backward = straight backward movement
	//left forward and right backward = turn in place clockwise
	//left backward and right forward = turn in place counterclockwise
	//left forward only = car turn clockwise
	//right forward only = car turn counterclockwise
void moveWheels(){
	motor[leftFrontMotor] = .5*vexRT[Ch3];
	motor[leftBackMotor] = .5*vexRT[Ch3];
	motor[rightFrontMotor] = .5*-vexRT[Ch2];
	motor[rightBackMotor] = .5*-vexRT[Ch2];
}

//opens or closes claw
	//if 6U is pressed, it opens
	//if 6D is pressed, it closes
void updateClaw()
{
    if(vexRT[Btn6U] == 1) // If upper Z button down
        motor[claw] = 25;
    else if(vexRT[Btn6D] == 1) // If lower Z button down
        motor[claw] = -25;
    else
    	motor[claw] = 0;
}

//raises, lowers, or stops moving the arm depending if button 5U, 5D, or neither are pressed
void updateArm()
{
	int power = 0;

	if(vexRT[Btn5U] == 1) //if left upper Z button is pressed
	{
		power += 60;
		motor[armLeft] = -50-power;
		motor[armRight] = 50+power;
	}
	else if(vexRT[Btn5D] == 1) //if left lower Z button is pressed
	{
		power += 1;
		motor[armLeft] = -7-power;
		motor[armRight] = 6+power;
	}
	else
	{
		motor[armLeft] = -30;
		motor[armRight] = 30;
	}
}


//*************************
//          TASKS
//*************************

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

  // All activities that occur before the competition starts
  // Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
  auto();
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
  // User control code here, inside the loop

  while (true)
  {
    moveWheels();
		updateClaw();
		updateArm();
  }
}
