#pragma config(Motor,  port2,           leftFront,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           leftBack,      tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           rightFront,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           rightBack,     tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void moveWheels(int wheelPower, int curve)
{
	/*
	curve -> (left, right)
	-128 -> (-wheelPower, wheelPower)
	-64 -> (0, wheelPower)
	0 -> (wheelPower, wheelPower)
	64 -> (wheelPower, 0)
	128 -> wheelPower, -wheelPower)
	*/

	// Amount to lower wheelPower on respective wheel
	int curveMod = abs(curve)*wheelPower*2/128;

	// Start left and right at wheelPower, then subtract curveMod from one of them
	int left, right;
	left = right = wheelPower;
	if (curve < 0) left -= curveMod;
	else right -= curveMod;

	// Set left and right motors
	motor[leftFront] = -left;
	motor[leftBack] = -left;
	motor[rightFront] = right;
	motor[rightBack] = right;
}

task main()
{
	while (true) {
		moveWheels(vexRT[Ch1], vexRT[Ch2]);
	}
}
